from django.urls import path

from .views import (
    AdminAccountListUpdateView,
    CompanyWorkdayConfigurationView,
    DepartmentListView,
    DepartmentDetailView,
    EmailConfigView,
    EmploymentTypeListView,
    EmploymentTypeDetailView,
    LineListView,
    LineDetailView,
    MemoAdvertisementDetailView,
    MemoAdvertisementListCreateView,
    MemoAdvertisementSettingsView,
    OfficeDetailView,
    OfficeListCreateView,
    PasswordPolicyAdminView,
    PasswordPolicyReadView,
    PositionDetailView,
    PositionListView,
    ShiftDetailView,
    ShiftListCreateView,
    TestEmailView,
)

urlpatterns = [
    path('admin-accounts', AdminAccountListUpdateView.as_view(), name='admin-accounts-list'),
    path('admin-accounts/<int:pk>', AdminAccountListUpdateView.as_view(), name='admin-accounts-detail'),
    path('email-config', EmailConfigView.as_view(), name='email-config'),
    path('email-config/test', TestEmailView.as_view(), name='email-config-test'),
    path('memo-advertisement', MemoAdvertisementSettingsView.as_view(), name='memo-advertisement-settings'),
    path('memo-advertisement/memos', MemoAdvertisementListCreateView.as_view(), name='memo-advertisement-memos'),
    path('memo-advertisement/memos/<int:pk>', MemoAdvertisementDetailView.as_view(), name='memo-advertisement-memo-detail'),
    path('password-policy', PasswordPolicyReadView.as_view(), name='password-policy'),
    path('password-policy/admin', PasswordPolicyAdminView.as_view(), name='password-policy-admin'),
    path('workday-schedule', CompanyWorkdayConfigurationView.as_view(), name='workday-schedule'),
    path('shifts', ShiftListCreateView.as_view(), name='shifts-list-create'),
    path('shifts/<int:pk>', ShiftDetailView.as_view(), name='shifts-detail'),
    path('offices', OfficeListCreateView.as_view(), name='offices-list-create'),
    path('offices/<int:pk>', OfficeDetailView.as_view(), name='offices-detail'),
    path('departments', DepartmentListView.as_view(), name='departments-list-create'),
    path('departments/<int:pk>', DepartmentDetailView.as_view(), name='departments-detail'),
    path('lines', LineListView.as_view(), name='lines-list-create'),
    path('lines/<int:pk>', LineDetailView.as_view(), name='lines-detail'),
    path('positions', PositionListView.as_view(), name='positions-list-create'),
    path('positions/<int:pk>', PositionDetailView.as_view(), name='positions-detail'),
    path('employment-types', EmploymentTypeListView.as_view(), name='employment-types-list-create'),
    path('employment-types/<int:pk>', EmploymentTypeDetailView.as_view(), name='employment-types-detail'),
]

