# Generated by Django 6.0.3 on 2026-04-21 02:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='draft', max_length=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[('all_users', 'All Users'), ('specific_users', 'Specific Users')], default='all_users', max_length=15)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'survey_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('dropdown', 'Dropdown'), ('rating', 'Rating Scale'), ('likert', 'Likert Scale'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('yes_no', 'Yes / No'), ('number', 'Number'), ('date', 'Date'), ('linear_scale', 'Linear Scale')], default='short_text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('show_percentage_summary', models.BooleanField(default=False)),
                ('allow_other', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'db_table': 'survey_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.surveyquestion')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'db_table': 'survey_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionRatingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.PositiveSmallIntegerField(default=1)),
                ('max_value', models.PositiveSmallIntegerField(default=5)),
                ('min_label', models.CharField(blank=True, default='', max_length=100)),
                ('max_label', models.CharField(blank=True, default='', max_length=100)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_config', to='survey.surveyquestion')),
            ],
            options={
                'verbose_name': 'Rating Config',
                'verbose_name_plural': 'Rating Configs',
                'db_table': 'survey_question_rating_configs',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'db_table': 'survey_responses',
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_survey_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Template',
                'verbose_name_plural': 'Survey Templates',
                'db_table': 'survey_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.surveytemplate'),
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, default='', max_length=5000)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('other_text', models.CharField(blank=True, default='', max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveyquestion')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='answers', to='survey.surveyquestionoption')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveyresponse')),
            ],
            options={
                'verbose_name': 'Survey Answer',
                'verbose_name_plural': 'Survey Answers',
                'db_table': 'survey_answers',
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SurveyTargetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_users', to='survey.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Target User',
                'verbose_name_plural': 'Survey Target Users',
                'db_table': 'survey_target_users',
                'unique_together': {('survey', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('survey__isnull', False), ('template__isnull', True)), models.Q(('survey__isnull', True), ('template__isnull', False)), _connector='OR'), name='survey_question_exactly_one_parent'),
        ),
    ]
