# Generated by Django 6.0.3 on 2026-04-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='template_type',
            field=models.CharField(blank=True, choices=[('Leadership Alignment', 'Leadership Alignment'), ('Engagement', 'Engagement'), ('Effectiveness', 'Effectiveness'), ('Experience', 'Experience'), ('Onboarding', 'Onboarding')], db_index=True, default='', max_length=50),
        ),
    ]
