# Generated by Django 6.0.3 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_add_template_type_to_surveytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='template_type',
            field=models.CharField(blank=True, choices=[
                ('Leadership Alignment', 'Leadership Alignment'),
                ('Engagement', 'Engagement'),
                ('Effectiveness', 'Effectiveness'),
                ('Experience', 'Experience'),
                ('Onboarding', 'Onboarding'),
            ], db_index=True, default='', max_length=50),
        ),
    ]
