# Generated by Django 6.0.3 on 2026-05-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveytargetuser_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('dropdown', 'Dropdown'), ('rating', 'Rating Scale'), ('likert', 'Likert Scale'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('yes_no', 'Yes / No'), ('number', 'Number'), ('date', 'Date'), ('linear_scale', 'Linear Scale'), ('section', 'Section'), ('subsection', 'Subsection'), ('statement', 'Statement')], default='short_text', max_length=20),
        ),
    ]
