# Generated by Django 5.0.3 on 2026-04-09 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prForm', '0002_emergencyloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prf_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_allowance', to='prForm.prfrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
