# Generated by Django 6.0.3 on 2026-04-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prForm', '0003_medicineallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfrequest',
            name='seen',
            field=models.BooleanField(default=True),
        ),
    ]
