from django.urls import path

from .views import (
    FinanceAllowanceTemplateView,
    FinanceChartView,
    FinanceDeductionTemplateView,
    FinanceEmployeeDetailView,
    FinanceEmployeeFilterOptionsView,
    FinanceEmployeeListView,
    FinanceExportView,
    FinanceImportView,
    FinanceLoanDeductionsView,
    FinancePayslipDeleteView,
    FinancePayslipUploadView,
    FinancePrincipalBalanceTemplateView,
    FinanceSavingsTemplateView,
    FinanceSavingsWithdrawView,
    FinanceTypeCRUDView,
    FinanceTypeListView,
    LoanSettingsView,
    OfficeFinanceRateView,
    UserFinanceLoanDeductionsView,
    UserFinanceLoanSettingsView,
    UserFinancePayslipSendEmailView,
    UserFinanceRecordsView,
)

urlpatterns = [
    path('admin/types',           FinanceTypeListView.as_view(),       name='finance-types'),
    path('admin/types/create',    FinanceTypeCRUDView.as_view(),       name='finance-type-create'),
    path('admin/types/<int:pk>',  FinanceTypeCRUDView.as_view(),       name='finance-type-detail'),
    path('admin/chart',           FinanceChartView.as_view(),          name='finance-chart'),
    path('admin/employees',       FinanceEmployeeListView.as_view(),   name='finance-employees'),
    path('admin/employees/<str:idnumber>/records', FinanceEmployeeDetailView.as_view(), name='finance-employee-records'),
    path('admin/employee-filters', FinanceEmployeeFilterOptionsView.as_view(), name='finance-employee-filters'),
    path('admin/import',          FinanceImportView.as_view(),         name='finance-import'),
    path('admin/export',          FinanceExportView.as_view(),         name='finance-export'),
    path('admin/template/principal-balance', FinancePrincipalBalanceTemplateView.as_view(), name='finance-template-principal-balance'),
    path('admin/template/deduction',         FinanceDeductionTemplateView.as_view(),        name='finance-template-deduction'),
    path('admin/template/allowance',         FinanceAllowanceTemplateView.as_view(),        name='finance-template-allowance'),
    path('admin/template/savings',            FinanceSavingsTemplateView.as_view(),          name='finance-template-savings'),
    path('admin/payslip-upload',  FinancePayslipUploadView.as_view(),  name='finance-payslip-upload'),
    path('admin/payslips/<int:pk>', FinancePayslipDeleteView.as_view(), name='finance-payslip-delete'),
    path('admin/loans/<int:pk>/deductions', FinanceLoanDeductionsView.as_view(), name='finance-loan-deductions'),
    path('admin/savings/<int:pk>/withdraw', FinanceSavingsWithdrawView.as_view(), name='finance-savings-withdraw'),
    path('admin/loan-settings',             LoanSettingsView.as_view(),           name='finance-loan-settings'),
    path('admin/office-rates',    OfficeFinanceRateView.as_view(),     name='finance-office-rates'),
    path('admin/office-rates/<int:pk>', OfficeFinanceRateView.as_view(), name='finance-office-rates-detail'),

    # ── User-facing endpoints ───────────────────────────────────────────────
    path('my/records',                               UserFinanceRecordsView.as_view(),           name='finance-my-records'),
    path('my/loans/<int:pk>/deductions',             UserFinanceLoanDeductionsView.as_view(),    name='finance-my-loan-deductions'),
    path('my/payslips/<int:pk>/send-email',          UserFinancePayslipSendEmailView.as_view(),  name='finance-my-payslip-send-email'),
    path('my/loan-settings',                         UserFinanceLoanSettingsView.as_view(),      name='finance-my-loan-settings'),
]
