# Generated by Django 6.0.3 on 2026-04-15 05:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('has_balance', models.BooleanField(default=True, help_text='Whether entitled-leave balance is tracked for this type.')),
                ('deductible', models.BooleanField(default=True, help_text="Whether approved leave deducts from the employee's balance.")),
                ('requires_clinic_approval', models.BooleanField(default=False, help_text='If True, a Clinic step is inserted first in the routing chain.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveSubreason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreasons', to='leave.leavereason')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('reason', 'title')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('days_count', models.PositiveSmallIntegerField()),
                ('is_deductible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('routing', 'Routing'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('control_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_prepared', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('manager_disapproved', models.BooleanField(default=False)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavereason')),
                ('subreason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='leave.leavesubreason')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leavereason',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_group', models.CharField(choices=[('manager', 'Manager'), ('clinic', 'Clinic'), ('iad', 'IAD'), ('hr', 'HR')], max_length=10)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_steps_acted', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_steps_as_approver', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='leave.leaverequest')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('leave_request', 'sequence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='leavereason',
            unique_together={('leave_type', 'title')},
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('entitled_leave', models.DecimalField(decimal_places=1, max_digits=6)),
                ('used_leave', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('employee', 'leave_type', 'period_start', 'period_end')},
            },
        ),
    ]
