# Generated by Django 6.0.3 on 2026-04-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_reason_leave_types_m2m'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavereason',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leavereason',
            name='leave_type',
        ),
    ]
