# Generated by Django 6.0.3 on 2026-04-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leavereason_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
