# Generated by Django 6.0.3 on 2026-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leave_activated_at_cancelled_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapprovalstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('skipped', 'Skipped')], default='pending', max_length=15),
        ),
    ]
