# Generated by Django 6.0.3 on 2026-04-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0005_employmenttype_position'),
        ('leave', '0006_add_skipped_step_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Human-readable label for this rule, e.g. "Clerk / Line Leader route".', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positions', models.ManyToManyField(help_text='Requestor positions this rule applies to.', related_name='routing_rules', to='generalsettings.position')),
            ],
            options={
                'verbose_name': 'Leave Routing Rule',
                'verbose_name_plural': 'Leave Routing Rules',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(help_text='Execution order of this step (1 = first middle step).')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='leave.leaveroutingrule')),
                ('target_positions', models.ManyToManyField(help_text='The set of positions to match during approver-chain traversal. The first chain member whose position is in this set becomes the approver.', related_name='routing_step_targets', to='generalsettings.position')),
            ],
            options={
                'verbose_name': 'Leave Routing Step',
                'verbose_name_plural': 'Leave Routing Steps',
                'ordering': ['step_order'],
                'unique_together': {('rule', 'step_order')},
            },
        ),
    ]
