# Generated by Django 6.0.3 on 2026-04-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0005_employmenttype_position'),
        ('leave', '0007_add_routing_rule_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveroutingrule',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Requestor departments this rule applies to.  Leave empty to apply to the matched positions across ALL departments.', related_name='routing_rules', to='generalsettings.department'),
        ),
    ]
