# Generated by Django 6.0.3 on 2026-03-07 00:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredentials',
            name='idnumber',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='logincredentials',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
