# Generated by Django 6.0.3 on 2026-03-09 09:56

import userLogin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_alter_logincredentials_idnumber_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logincredentials',
            managers=[
                ('objects', userLogin.models.LoginCredentialsManager()),
            ],
        ),
    ]
