# Generated by Django 6.0.3 on 2026-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0003_alter_logincredentials_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredentials',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/'),
        ),
    ]
