# Generated by Django 6.0.3 on 2026-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0005_employeesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredentials',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
    ]
