# Generated by Django 6.0.3 on 2026-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0006_logincredentials_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredentials',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
