# Generated by Django 6.0.3 on 2026-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0007_add_locked_at_and_system_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredentials',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logincredentials',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
