# Generated by Django 6.0.3 on 2026-03-24 05:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_change_on_first_login', models.BooleanField(default=True, help_text='Force password change when a user logs in for the first time.')),
                ('min_length', models.PositiveSmallIntegerField(default=8, help_text='Minimum number of characters (6 – 64).', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(64)])),
                ('require_uppercase', models.BooleanField(default=True, help_text='Password must contain at least one uppercase letter (A–Z).')),
                ('require_lowercase', models.BooleanField(default=True, help_text='Password must contain at least one lowercase letter (a–z).')),
                ('require_number', models.BooleanField(default=True, help_text='Password must contain at least one digit (0–9).')),
                ('require_special_character', models.BooleanField(default=False, help_text='Password must contain at least one special character (!@#$%^&* …).')),
            ],
            options={
                'verbose_name': 'Password Policy',
                'verbose_name_plural': 'Password Policy',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Name contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='generalsettings.office')),
            ],
            options={
                'ordering': ['office', 'name'],
                'unique_together': {('name', 'office')},
            },
        ),
        migrations.AddField(
            model_name='office',
            name='shifts',
            field=models.ManyToManyField(blank=True, help_text='Shifts that are active in this office.', related_name='offices', to='generalsettings.shift'),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='generalsettings.department')),
            ],
            options={
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
    ]
