# Generated by Django 6.0.3 on 2026-03-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('sendgrid', 'SendGrid'), ('outlook', 'Outlook / Office 365'), ('custom', 'Custom SMTP')], default='gmail', max_length=20)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL (port 465).')),
                ('use_tls', models.BooleanField(default=True, help_text='Use STARTTLS (port 587).')),
                ('username', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('from_name', models.CharField(blank=True, help_text='Display name shown in the From field.', max_length=100)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
