# Generated by Django 5.0.3 on 2026-03-30 03:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0002_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='allowance_day',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Allowance day (numeric rate).', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='office',
            name='legal_holiday_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Legal holiday rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='office',
            name='nd_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Regular night-differential overtime rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='office',
            name='nd_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Regular night differential rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='office',
            name='ojt_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='OJT rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='office',
            name='regular_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Regular overtime rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='office',
            name='rest_day_ot_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Rest-day overtime rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='office',
            name='saturday_off_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Saturday-off rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
