# Generated by Django 5.0.3 on 2026-03-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0003_office_allowance_day_office_legal_holiday_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='allowance_day',
        ),
        migrations.RemoveField(
            model_name='office',
            name='legal_holiday_rate',
        ),
        migrations.RemoveField(
            model_name='office',
            name='nd_ot_rate',
        ),
        migrations.RemoveField(
            model_name='office',
            name='nd_rate',
        ),
        migrations.RemoveField(
            model_name='office',
            name='ojt_rate',
        ),
        migrations.RemoveField(
            model_name='office',
            name='regular_ot_rate',
        ),
        migrations.RemoveField(
            model_name='office',
            name='rest_day_ot_rate',
        ),
        migrations.RemoveField(
            model_name='office',
            name='saturday_off_rate',
        ),
    ]
