# Generated by Django 6.0.3 on 2026-04-10 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0004_auto_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
            ],
            options={
                'verbose_name': 'Employment Type',
                'verbose_name_plural': 'Employment Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('level_of_approval', models.PositiveSmallIntegerField(default=0, help_text='Hierarchical approval level (0 = lowest). Used to determine eligible approvers.')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-level_of_approval', 'name'],
            },
        ),
    ]
