# Generated by Django 6.0.3 on 2026-05-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0007_passwordpolicy_lockout_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorkdayConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdays', models.JSONField(default=list, help_text='List of working weekdays using Python weekday numbers (0=Mon ... 6=Sun).')),
            ],
            options={
                'verbose_name': 'Company Workday Configuration',
                'verbose_name_plural': 'Company Workday Configuration',
            },
        ),
    ]
