# Generated by Django 6.0.3 on 2026-05-26 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0010_companyworkdayconfiguration_weekday_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='from_address',
            field=models.EmailField(blank=True, help_text='From email address (defaults to username if blank).', max_length=255),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='min_length',
            field=models.PositiveSmallIntegerField(default=8, help_text='Minimum number of characters (6 – 128).', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(128)]),
        ),
    ]
