# Generated by Django 6.0.3 on 2026-05-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0011_emailconfiguration_from_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('active', models.BooleanField(default=True, help_text='Whether this memo is active and should be shown to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memo Advertisement',
                'verbose_name_plural': 'Memo Advertisements',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoAdvertisementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Toggle display of active memos on user-facing pages.')),
            ],
            options={
                'verbose_name': 'Memo Advertisement Settings',
                'verbose_name_plural': 'Memo Advertisement Settings',
            },
        ),
    ]
