# Generated by Django 6.0.3 on 2026-03-09 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('employee_id', models.CharField(blank=True, db_index=True, max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=17)),
                ('module', models.CharField(blank=True, db_index=True, max_length=100)),
                ('action', models.CharField(blank=True, db_index=True, max_length=255)),
                ('http_method', models.CharField(db_index=True, max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
    ]
