# Generated by Django 6.0.3 on 2026-03-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('prf_approved', 'PRF Request Approved'), ('prf_disapproved', 'PRF Request Disapproved'), ('prf_cancelled', 'PRF Request Cancelled'), ('certificate_issued', 'Certificate Issued')], db_index=True, max_length=30),
        ),
    ]
