# Generated by Django 6.0.3 on 2026-03-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_prf_control_number',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_prf_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
