# Generated by Django 6.0.3 on 2026-04-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0004_remove_notification_related_prf_control_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('prf_approved', 'PRF Request Approved'), ('prf_disapproved', 'PRF Request Disapproved'), ('prf_cancelled', 'PRF Request Cancelled'), ('certificate_issued', 'Certificate Issued'), ('password_reset', 'Password Reset by Administrator'), ('promotion', 'Position Promotion'), ('leave_approved', 'Leave Request Approved'), ('leave_disapproved', 'Leave Request Disapproved'), ('leave_pending_approval', 'Leave Request Pending Approval'), ('leave_cancelled', 'Leave Request Cancelled')], db_index=True, max_length=30),
        ),
    ]
