# Generated by Django 6.0.3 on 2026-04-21 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0005_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_scope',
            field=models.CharField(choices=[('specific_user', 'Specific User'), ('general', 'General')], db_index=True, default='specific_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('prf_approved', 'PRF Request Approved'), ('prf_disapproved', 'PRF Request Disapproved'), ('prf_cancelled', 'PRF Request Cancelled'), ('certificate_issued', 'Certificate Issued'), ('password_reset', 'Password Reset by Administrator'), ('promotion', 'Position Promotion'), ('leave_approved', 'Leave Request Approved'), ('leave_disapproved', 'Leave Request Disapproved'), ('leave_pending_approval', 'Leave Request Pending Approval'), ('leave_cancelled', 'Leave Request Cancelled'), ('survey_assigned', 'Survey Assigned'), ('survey_reminder', 'Survey Reminder')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
