# Generated by Django 6.0.3 on 2026-05-21 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0007_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'New Announcement'), ('prf_approved', 'PRF Request Approved'), ('prf_disapproved', 'PRF Request Disapproved'), ('prf_cancelled', 'PRF Request Cancelled'), ('certificate_issued', 'Certificate Issued'), ('password_reset', 'Password Reset by Administrator'), ('promotion', 'Position Promotion'), ('leave_approved', 'Leave Request Approved'), ('leave_disapproved', 'Leave Request Disapproved'), ('leave_pending_approval', 'Leave Request Pending Approval'), ('leave_cancelled', 'Leave Request Cancelled'), ('survey_assigned', 'Survey Assigned'), ('survey_reminder', 'Survey Reminder'), ('training_assigned', 'Training Evaluation Assigned'), ('training_submitted', 'Training Evaluation Submitted'), ('training_supervisor_review', 'Training Ready for Supervisor Review'), ('training_user_confirmation', 'Training Ready for Your Confirmation'), ('training_final_approval', 'Training Needs Final Approval'), ('training_returned', 'Training Returned for Re-evaluation'), ('training_completed', 'Training Evaluation Completed'), ('mis_ticket_created', 'MIS Ticket Created'), ('mis_ticket_updated', 'MIS Ticket Updated')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_type', models.CharField(choices=[('400', 'Bad Request'), ('401', 'Unauthorized'), ('403', 'Forbidden'), ('404', 'Not Found'), ('405', 'Method Not Allowed'), ('500', 'Internal Server Error'), ('502', 'Bad Gateway'), ('503', 'Service Unavailable'), ('unhandled_exception', 'Unhandled Exception'), ('validation_error', 'Validation Error'), ('database_error', 'Database Error'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('module', models.CharField(blank=True, db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Error Log',
                'verbose_name_plural': 'System Error Logs',
                'db_table': 'system_error_logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
    ]
