# Generated by Django 6.0.3 on 2026-05-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'New Announcement'), ('calendar_event', 'Calendar Event'), ('prf_approved', 'PRF Request Approved'), ('prf_disapproved', 'PRF Request Disapproved'), ('prf_cancelled', 'PRF Request Cancelled'), ('certificate_issued', 'Certificate Issued'), ('password_reset', 'Password Reset by Administrator'), ('promotion', 'Position Promotion'), ('leave_approved', 'Leave Request Approved'), ('leave_disapproved', 'Leave Request Disapproved'), ('leave_pending_approval', 'Leave Request Pending Approval'), ('leave_cancelled', 'Leave Request Cancelled'), ('survey_assigned', 'Survey Assigned'), ('survey_reminder', 'Survey Reminder'), ('training_assigned', 'Training Evaluation Assigned'), ('training_submitted', 'Training Evaluation Submitted'), ('training_supervisor_review', 'Training Ready for Supervisor Review'), ('training_user_confirmation', 'Training Ready for Your Confirmation'), ('training_final_approval', 'Training Needs Final Approval'), ('training_returned', 'Training Returned for Re-evaluation'), ('training_completed', 'Training Evaluation Completed'), ('mis_ticket_created', 'MIS Ticket Created'), ('mis_ticket_updated', 'MIS Ticket Updated'), ('finance_loan_uploaded', 'Loan Record Uploaded'), ('finance_deduction_uploaded', 'Loan Deduction Uploaded'), ('finance_savings_withdrawn', 'Savings Withdrawal Recorded')], db_index=True, max_length=30),
        ),
    ]
