# Generated by Django 6.0.3 on 2026-04-10 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0005_employmenttype_position'),
        ('userProfile', '0002_workinformation_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workinformation',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='The employee who approves requests submitted by this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='generalsettings.employmenttype'),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='hdmf_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='philhealth_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='generalsettings.position'),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='sss_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workinformation',
            name='tin_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Record',
                'verbose_name_plural': 'Child Records',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('degree', models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('year_attended', models.PositiveSmallIntegerField(blank=True, help_text='Year attended or year graduated (e.g. 2018).', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education Record',
                'verbose_name_plural': 'Education Records',
                'ordering': ['-year_attended', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('relationship', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('contact_number', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g. 09171234567 or +639171234567).', regex='^(\\+63|0)\\d{10}$')])),
                ('address', models.CharField(blank=True, default='', max_length=300, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='FamilyBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('father_name', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('spouse_name', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_background', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Background',
                'verbose_name_plural': 'Family Backgrounds',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('nickname', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('work_email', models.EmailField(blank=True, default='', max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not', 'Prefer Not to Say')], default='', max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, default='', max_length=150, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('contact_number', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g. 09171234567 or +639171234567).', regex='^(\\+63|0)\\d{10}$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='Philippines', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('province', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('city', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('barangay', models.CharField(blank=True, default='', max_length=150, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('street', models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('block_lot', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='present_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Present Address',
                'verbose_name_plural': 'Present Addresses',
            },
        ),
        migrations.CreateModel(
            name='ProvincialAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_as_present', models.BooleanField(default=False, help_text='When True the provincial address mirrors the present address.')),
                ('country', models.CharField(blank=True, default='Philippines', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('province', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('city', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('barangay', models.CharField(blank=True, default='', max_length=150, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('street', models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('block_lot', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provincial_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provincial Address',
                'verbose_name_plural': 'Provincial Addresses',
            },
        ),
    ]
