# Generated by Django 6.0.3 on 2026-04-10 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_workinformation_approver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
                'unique_together': {('employee', 'name')},
            },
        ),
    ]
