# Generated by Django 6.0.3 on 2026-04-13 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationrecord',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('vocational', 'Vocational'), ('tertiary', 'Tertiary')], default='', help_text='Education level for this record.', max_length=20, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')]),
        ),
    ]
