# Generated by Django 6.0.3 on 2026-05-02 02:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0006_alter_surveyquestion_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('speaker', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('training_date', models.DateField(db_index=True)),
                ('objective', models.TextField(blank=True, default='', max_length=1000, validators=[django.core.validators.RegexValidator(message='Field contains invalid characters.', regex='^[^<>{}\\[\\]\\\\|^~`"]*$')])),
                ('target_type', models.CharField(choices=[('all_users', 'All Users'), ('specific_users', 'Specific Users')], default='all_users', max_length=15)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Survey template whose questions are deep-copied into this training.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='survey.surveytemplate')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'db_table': 'training_trainings',
                'ordering': ['-training_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_steps_as_approver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_approval_steps',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApproverEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='training.trainingapprovalstep')),
            ],
            options={
                'db_table': 'training_approver_evaluations',
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('dropdown', 'Dropdown'), ('rating', 'Rating Scale'), ('likert', 'Likert Scale'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('yes_no', 'Yes / No'), ('number', 'Number'), ('date', 'Date'), ('linear_scale', 'Linear Scale'), ('section', 'Section'), ('subsection', 'Subsection'), ('statement', 'Statement')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_other', models.BooleanField(default=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.training')),
            ],
            options={
                'db_table': 'training_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='training.trainingquestion')),
            ],
            options={
                'db_table': 'training_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestionRatingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.PositiveSmallIntegerField(default=1)),
                ('max_value', models.PositiveSmallIntegerField(default=5)),
                ('min_label', models.CharField(blank=True, max_length=100)),
                ('max_label', models.CharField(blank=True, max_length=100)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_config', to='training.trainingquestion')),
            ],
            options={
                'db_table': 'training_question_rating_configs',
            },
        ),
        migrations.CreateModel(
            name='TrainingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('routing', 'Routing'), ('approved', 'Approved')], default='pending', max_length=15)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_submissions', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='training.training')),
            ],
            options={
                'db_table': 'training_submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('training', 'submitted_by')},
            },
        ),
        migrations.AddField(
            model_name='trainingapprovalstep',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='training.trainingsubmission'),
        ),
        migrations.CreateModel(
            name='TrainingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_participants',
                'unique_together': {('training', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ApproverEvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, max_length=5000)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('other_text', models.CharField(blank=True, max_length=500)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training.approverevaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_answers', to='training.trainingquestion')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='approver_answers', to='training.trainingquestionoption')),
            ],
            options={
                'db_table': 'training_approver_evaluation_answers',
                'unique_together': {('evaluation', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='trainingapprovalstep',
            unique_together={('submission', 'sequence')},
        ),
        migrations.CreateModel(
            name='TrainingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, max_length=5000)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('other_text', models.CharField(blank=True, max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='training.trainingquestion')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='user_answers', to='training.trainingquestionoption')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training.trainingsubmission')),
            ],
            options={
                'db_table': 'training_answers',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
