# Generated by Django 6.0.3 on 2026-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0005_employmenttype_position'),
        ('training', '0003_evaluation_routing_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationroutingrule',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Requestor departments this rule applies to. Leave empty to apply to the matched positions across ALL departments.', related_name='evaluation_routing_rules', to='generalsettings.department'),
        ),
        migrations.AlterField(
            model_name='evaluationroutingrule',
            name='description',
            field=models.CharField(blank=True, help_text='Human-readable label for this rule, e.g. "Clerk / Line Leader route".', max_length=200),
        ),
        migrations.AlterField(
            model_name='evaluationroutingrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluationroutingrule',
            name='module',
            field=models.CharField(choices=[('training_evaluation', 'Training Evaluation'), ('employee_evaluation', 'Employee Evaluation')], db_index=True, help_text='Which evaluation module this rule governs.', max_length=25),
        ),
        migrations.AlterField(
            model_name='evaluationroutingrule',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text='Requestor positions this rule applies to.', related_name='evaluation_routing_rules', to='generalsettings.position'),
        ),
        migrations.AlterField(
            model_name='evaluationroutingrulestep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluationroutingrulestep',
            name='step_order',
            field=models.PositiveSmallIntegerField(help_text='Execution order of this step within the rule (1 = first step, max 3).'),
        ),
        migrations.AlterField(
            model_name='evaluationroutingrulestep',
            name='target_positions',
            field=models.ManyToManyField(blank=True, help_text='The first chain member whose position is in this set becomes the approver for this step.', related_name='evaluation_routing_step_targets', to='generalsettings.position'),
        ),
    ]
