# Generated by Django 6.0.3 on 2026-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemCalendar', '0002_calendarevent_repetition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='note',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
