# Generated by Django 6.0.3 on 2026-03-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemCalendar', '0003_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('important', 'Important'), ('meeting', 'Meeting'), ('task', 'Task'), ('reminder', 'Reminder'), ('deadline', 'Deadline'), ('legal', 'Legal Holiday'), ('special', 'Special Holiday'), ('day_off', 'Day Off'), ('company', 'Company Holiday')], default='meeting', max_length=20),
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
