# Generated by Django 6.0.3 on 2026-03-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemCalendar', '0004_alter_calendarevent_event_type_delete_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
