# Generated by Django 6.0.3 on 2026-05-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='misticket',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='misdevice',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('phone', 'Phone / IP Phone'), ('router', 'Router / Switch'), ('monitor', 'Monitor'), ('projector', 'Projector'), ('ups', 'UPS'), ('network', 'Network Device'), ('peripheral', 'Peripheral'), ('other', 'Other')], max_length=20),
        ),
    ]
