# Generated by Django 6.0.3 on 2026-05-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_ticket', '0002_add_subject_to_misticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='misticket',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='mis_ticket.misdevice'),
        ),
        migrations.AddField(
            model_name='misticket',
            name='seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='misticketdiagnosis',
            name='recommended_parts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='misticketdiagnosis',
            name='requires_immediate_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='misticket',
            name='category',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network'), ('account', 'Account / Access'), ('printer', 'Printer / Scanner'), ('email', 'Email'), ('request_for_parts', 'Request for Parts'), ('other', 'Other')], max_length=20),
        ),
    ]
