# Generated by Django 5.0.3 on 2026-03-30 04:16

import django.core.validators
import django.db.models.deletion
import finance.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('generalsettings', '0004_auto_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='net_pay',
        ),
        migrations.AddField(
            model_name='payslip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), finance.models._validate_payslip_pdf]),
        ),
        migrations.CreateModel(
            name='OfficeFinanceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojt_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='On-the-job training hourly rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allowance_day', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Daily allowance rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nd_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Regular night-differential rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nd_ot_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Night-differential overtime rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('regular_ot_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Regular overtime rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rest_day_ot_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Rest-day overtime rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('legal_holiday_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Legal holiday rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('saturday_off_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Saturday-off rate.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_rate', to='generalsettings.office')),
            ],
            options={
                'db_table': 'finance_office_rates',
                'ordering': ['office'],
            },
        ),
    ]
