# Generated by Django 6.0.3 on 2026-04-06 08:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_allowancetype_percentage_allowance_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='withdraw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='savings',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
