# Generated by Django 5.0.3 on 2026-04-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_withdraw_to_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_frequency', models.CharField(choices=[('cutoff', 'Cut-Off (Cut-off ×2)'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='cutoff', help_text='How often loan deductions are applied across the system.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_loan_settings',
            },
        ),
    ]
