# Generated by Django 6.0.3 on 2026-05-29 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_loan_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTPayslipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_off', models.CharField(max_length=100)),
                ('period_covered', models.CharField(blank=True, max_length=100, null=True)),
                ('regular_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nd_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_school_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_ojt_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_ojt_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rice_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ot_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nd_ot_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('legal_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('satoff_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rd_ot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ot_pay_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_allow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rd_ot_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perfect_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
