# Generated by Django 6.0.3 on 2026-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_ojt_payslip_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ojtpayslipdata',
            name='holiday_hours',
        ),
        migrations.RemoveField(
            model_name='ojtpayslipdata',
            name='rd_ot_days',
        ),
        migrations.AddField(
            model_name='ojtpayslipdata',
            name='holiday_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ojtpayslipdata',
            name='rd_ot_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
